
/* EDIFICIO BANCO REGIONAL*/
function mostrarDivMenu(){
	document.getElementById('inicioMain').style.opacity = 0.9;
	document.getElementById('ventSist17').style.opacity = 0;
	document.getElementById('ventSist16').style.opacity = 0;
	document.getElementById('ventSist15').style.opacity = 0;
	document.getElementById('ventSist14').style.opacity = 0;
	document.getElementById('ventSist13').style.opacity = 0;
	document.getElementById('ventSist12').style.opacity = 0;
	document.getElementById('ventSist11').style.opacity = 0;
	document.getElementById('ventSist10').style.opacity = 0;
	document.getElementById('ventSist9').style.opacity = 0;
	document.getElementById('ventSist8').style.opacity = 0;
	document.getElementById('ventSist7').style.opacity = 0;
	document.getElementById('ventSist6').style.opacity = 0;
	document.getElementById('ventSist5').style.opacity = 0;
	document.getElementById('ventSistA').style.opacity = 0;
	document.getElementById('ventSistB').style.opacity = 0;
	document.getElementById('ventSistC').style.opacity = 0;
	document.getElementById('ventUPS').style.opacity = 0;
	document.getElementById('ventCAD').style.opacity = 0;
	document.getElementById('ventCE').style.opacity = 0;
	document.getElementById('ventCR').style.opacity = 0;
	};
	function mostrarDivSist17(){
	document.getElementById('inicioMain').style.opacity = 0;
	document.getElementById('ventSist17').style.opacity = 0.9;
	document.getElementById('ventSist16').style.opacity = 0;
	document.getElementById('ventSist15').style.opacity = 0;
	document.getElementById('ventSist14').style.opacity = 0;
	document.getElementById('ventSist13').style.opacity = 0;
	document.getElementById('ventSist12').style.opacity = 0;
	document.getElementById('ventSist11').style.opacity = 0;
	document.getElementById('ventSist10').style.opacity = 0;
	document.getElementById('ventSist9').style.opacity = 0;
	document.getElementById('ventSist8').style.opacity = 0;
	document.getElementById('ventSist7').style.opacity = 0;
	document.getElementById('ventSist6').style.opacity = 0;
	document.getElementById('ventSist5').style.opacity = 0;
	document.getElementById('ventSistA').style.opacity = 0;
	document.getElementById('ventSistB').style.opacity = 0;
	document.getElementById('ventSistC').style.opacity = 0;
	document.getElementById('ventUPS').style.opacity = 0;
	document.getElementById('ventCAD').style.opacity = 0;
	document.getElementById('ventCE').style.opacity = 0;
	document.getElementById('ventCR').style.opacity = 0;
	};
	function mostrarDivSist16(){
	document.getElementById('inicioMain').style.opacity = 0;
	document.getElementById('ventSist17').style.opacity = 0;
	document.getElementById('ventSist16').style.opacity = 0.9;
	document.getElementById('ventSist15').style.opacity = 0;
	document.getElementById('ventSist14').style.opacity = 0;
	document.getElementById('ventSist13').style.opacity = 0;
	document.getElementById('ventSist12').style.opacity = 0;
	document.getElementById('ventSist11').style.opacity = 0;
	document.getElementById('ventSist10').style.opacity = 0;
	document.getElementById('ventSist9').style.opacity = 0;
	document.getElementById('ventSist8').style.opacity = 0;
	document.getElementById('ventSist7').style.opacity = 0;
	document.getElementById('ventSist6').style.opacity = 0;
	document.getElementById('ventSist5').style.opacity = 0;
	document.getElementById('ventSistA').style.opacity = 0;
	document.getElementById('ventSistB').style.opacity = 0;
	document.getElementById('ventSistC').style.opacity = 0;
	document.getElementById('ventUPS').style.opacity = 0;
	document.getElementById('ventCAD').style.opacity = 0;
	document.getElementById('ventCE').style.opacity = 0;
	document.getElementById('ventCR').style.opacity = 0;
	};
	function mostrarDivSist15(){
	document.getElementById('inicioMain').style.opacity = 0;
	document.getElementById('ventSist17').style.opacity = 0;
	document.getElementById('ventSist16').style.opacity = 0;
	document.getElementById('ventSist15').style.opacity = 0.9;
	document.getElementById('ventSist14').style.opacity = 0;
	document.getElementById('ventSist13').style.opacity = 0;
	document.getElementById('ventSist12').style.opacity = 0;
	document.getElementById('ventSist11').style.opacity = 0;
	document.getElementById('ventSist10').style.opacity = 0;
	document.getElementById('ventSist9').style.opacity = 0;
	document.getElementById('ventSist8').style.opacity = 0;
	document.getElementById('ventSist7').style.opacity = 0;
	document.getElementById('ventSist6').style.opacity = 0;
	document.getElementById('ventSist5').style.opacity = 0;
	document.getElementById('ventSistA').style.opacity = 0;
	document.getElementById('ventSistB').style.opacity = 0;
	document.getElementById('ventSistC').style.opacity = 0;
	document.getElementById('ventUPS').style.opacity = 0;
	document.getElementById('ventCAD').style.opacity = 0;
	document.getElementById('ventCE').style.opacity = 0;
	document.getElementById('ventCR').style.opacity = 0;
	};
	function mostrarDivSist14(){
	document.getElementById('inicioMain').style.opacity = 0;
	document.getElementById('ventSist17').style.opacity = 0;
	document.getElementById('ventSist16').style.opacity = 0;
	document.getElementById('ventSist15').style.opacity = 0;
	document.getElementById('ventSist14').style.opacity = 0.9;
	document.getElementById('ventSist13').style.opacity = 0;
	document.getElementById('ventSist12').style.opacity = 0;
	document.getElementById('ventSist11').style.opacity = 0;
	document.getElementById('ventSist10').style.opacity = 0;
	document.getElementById('ventSist9').style.opacity = 0;
	document.getElementById('ventSist8').style.opacity = 0;
	document.getElementById('ventSist7').style.opacity = 0;
	document.getElementById('ventSist6').style.opacity = 0;
	document.getElementById('ventSist5').style.opacity = 0;
	document.getElementById('ventSistA').style.opacity = 0;
	document.getElementById('ventSistB').style.opacity = 0;
	document.getElementById('ventSistC').style.opacity = 0;
	document.getElementById('ventUPS').style.opacity = 0;
	document.getElementById('ventCAD').style.opacity = 0;
	document.getElementById('ventCE').style.opacity = 0;
	document.getElementById('ventCR').style.opacity = 0;
	};
	function mostrarDivSist13(){
	document.getElementById('inicioMain').style.opacity = 0;
	document.getElementById('ventSist17').style.opacity = 0;
	document.getElementById('ventSist16').style.opacity = 0;
	document.getElementById('ventSist15').style.opacity = 0;
	document.getElementById('ventSist14').style.opacity = 0;
	document.getElementById('ventSist13').style.opacity = 0.9;
	document.getElementById('ventSist12').style.opacity = 0;
	document.getElementById('ventSist11').style.opacity = 0;
	document.getElementById('ventSist10').style.opacity = 0;
	document.getElementById('ventSist9').style.opacity = 0;
	document.getElementById('ventSist8').style.opacity = 0;
	document.getElementById('ventSist7').style.opacity = 0;
	document.getElementById('ventSist6').style.opacity = 0;
	document.getElementById('ventSist5').style.opacity = 0;
	document.getElementById('ventSistA').style.opacity = 0;
	document.getElementById('ventSistB').style.opacity = 0;
	document.getElementById('ventSistC').style.opacity = 0;
	document.getElementById('ventUPS').style.opacity = 0;
	document.getElementById('ventCAD').style.opacity = 0;
	document.getElementById('ventCE').style.opacity = 0;
	document.getElementById('ventCR').style.opacity = 0;
	};


	function mostrarDivSist12(){
	document.getElementById('inicioMain').style.opacity = 0;
	document.getElementById('ventSist17').style.opacity = 0;
	document.getElementById('ventSist16').style.opacity = 0;
	document.getElementById('ventSist15').style.opacity = 0;
	document.getElementById('ventSist14').style.opacity = 0;
	document.getElementById('ventSist13').style.opacity = 0;
	document.getElementById('ventSist12').style.opacity = 0.9;
	document.getElementById('ventSist11').style.opacity = 0;
	document.getElementById('ventSist10').style.opacity = 0;
	document.getElementById('ventSist9').style.opacity = 0;
	document.getElementById('ventSist8').style.opacity = 0;
	document.getElementById('ventSist7').style.opacity = 0;
	document.getElementById('ventSist6').style.opacity = 0;
	document.getElementById('ventSist5').style.opacity = 0;
	document.getElementById('ventSistA').style.opacity = 0;
	document.getElementById('ventSistB').style.opacity = 0;
	document.getElementById('ventSistC').style.opacity = 0;
	document.getElementById('ventUPS').style.opacity = 0;
	document.getElementById('ventCAD').style.opacity = 0;
	document.getElementById('ventCE').style.opacity = 0;
	document.getElementById('ventCR').style.opacity = 0;
	};
	function mostrarDivSist11(){
	document.getElementById('inicioMain').style.opacity = 0;
	document.getElementById('ventSist17').style.opacity = 0;
	document.getElementById('ventSist16').style.opacity = 0;
	document.getElementById('ventSist15').style.opacity = 0;
	document.getElementById('ventSist14').style.opacity = 0;
	document.getElementById('ventSist13').style.opacity = 0;
	document.getElementById('ventSist12').style.opacity = 0;
	document.getElementById('ventSist11').style.opacity = 0.9;
	document.getElementById('ventSist10').style.opacity = 0;
	document.getElementById('ventSist9').style.opacity = 0;
	document.getElementById('ventSist8').style.opacity = 0;
	document.getElementById('ventSist7').style.opacity = 0;
	document.getElementById('ventSist6').style.opacity = 0;
	document.getElementById('ventSist5').style.opacity = 0;
	document.getElementById('ventSistA').style.opacity = 0;
	document.getElementById('ventSistB').style.opacity = 0;
	document.getElementById('ventSistC').style.opacity = 0;
	document.getElementById('ventUPS').style.opacity = 0;
	document.getElementById('ventCAD').style.opacity = 0;
	document.getElementById('ventCE').style.opacity = 0;
	document.getElementById('ventCR').style.opacity = 0;
	};
	function mostrarDivSist10(){
	document.getElementById('inicioMain').style.opacity = 0;
	document.getElementById('ventSist17').style.opacity = 0;
	document.getElementById('ventSist16').style.opacity = 0;
	document.getElementById('ventSist15').style.opacity = 0;
	document.getElementById('ventSist14').style.opacity = 0;
	document.getElementById('ventSist13').style.opacity = 0;
	document.getElementById('ventSist12').style.opacity = 0;
	document.getElementById('ventSist11').style.opacity = 0;
	document.getElementById('ventSist10').style.opacity = 0.9;
	document.getElementById('ventSist9').style.opacity = 0;
	document.getElementById('ventSist8').style.opacity = 0;
	document.getElementById('ventSist7').style.opacity = 0;
	document.getElementById('ventSist6').style.opacity = 0;
	document.getElementById('ventSist5').style.opacity = 0;
	document.getElementById('ventSistA').style.opacity = 0;
	document.getElementById('ventSistB').style.opacity = 0;
	document.getElementById('ventSistC').style.opacity = 0;
	document.getElementById('ventUPS').style.opacity = 0;
	document.getElementById('ventCAD').style.opacity = 0;
	document.getElementById('ventCE').style.opacity = 0;
	document.getElementById('ventCR').style.opacity = 0;
	};
	function mostrarDivSist9(){
	document.getElementById('inicioMain').style.opacity = 0;
	document.getElementById('ventSist17').style.opacity = 0;
	document.getElementById('ventSist16').style.opacity = 0;
	document.getElementById('ventSist15').style.opacity = 0;
	document.getElementById('ventSist14').style.opacity = 0;
	document.getElementById('ventSist13').style.opacity = 0;
	document.getElementById('ventSist12').style.opacity = 0;
	document.getElementById('ventSist11').style.opacity = 0;
	document.getElementById('ventSist10').style.opacity = 0;
	document.getElementById('ventSist9').style.opacity = 0.9;
	document.getElementById('ventSist8').style.opacity = 0;
	document.getElementById('ventSist7').style.opacity = 0;
	document.getElementById('ventSist6').style.opacity = 0;
	document.getElementById('ventSist5').style.opacity = 0;
	document.getElementById('ventSistA').style.opacity = 0;
	document.getElementById('ventSistB').style.opacity = 0;
	document.getElementById('ventSistC').style.opacity = 0;
	document.getElementById('ventUPS').style.opacity = 0;
	document.getElementById('ventCAD').style.opacity = 0;
	document.getElementById('ventCE').style.opacity = 0;
	document.getElementById('ventCR').style.opacity = 0;
	};
	function mostrarDivSist8(){
	document.getElementById('inicioMain').style.opacity = 0;
	document.getElementById('ventSist17').style.opacity = 0;
	document.getElementById('ventSist16').style.opacity = 0;
	document.getElementById('ventSist15').style.opacity = 0;
	document.getElementById('ventSist14').style.opacity = 0;
	document.getElementById('ventSist13').style.opacity = 0;
	document.getElementById('ventSist12').style.opacity = 0;
	document.getElementById('ventSist11').style.opacity = 0;
	document.getElementById('ventSist10').style.opacity = 0;
	document.getElementById('ventSist9').style.opacity = 0;
	document.getElementById('ventSist8').style.opacity = 0.8;
	document.getElementById('ventSist7').style.opacity = 0;
	document.getElementById('ventSist6').style.opacity = 0;
	document.getElementById('ventSist5').style.opacity = 0;
	document.getElementById('ventSistA').style.opacity = 0;
	document.getElementById('ventSistB').style.opacity = 0;
	document.getElementById('ventSistC').style.opacity = 0;
	document.getElementById('ventUPS').style.opacity = 0;
	document.getElementById('ventCAD').style.opacity = 0;
	document.getElementById('ventCE').style.opacity = 0;
	document.getElementById('ventCR').style.opacity = 0;
	};
	function mostrarDivSist7(){
	document.getElementById('inicioMain').style.opacity = 0;
	document.getElementById('ventSist17').style.opacity = 0;
	document.getElementById('ventSist16').style.opacity = 0;
	document.getElementById('ventSist15').style.opacity = 0;
	document.getElementById('ventSist14').style.opacity = 0;
	document.getElementById('ventSist13').style.opacity = 0;
	document.getElementById('ventSist12').style.opacity = 0;
	document.getElementById('ventSist11').style.opacity = 0;
	document.getElementById('ventSist10').style.opacity = 0;
	document.getElementById('ventSist9').style.opacity = 0;
	document.getElementById('ventSist8').style.opacity = 0;
	document.getElementById('ventSist7').style.opacity = 0.9;
	document.getElementById('ventSist6').style.opacity = 0;
	document.getElementById('ventSist5').style.opacity = 0;
	document.getElementById('ventSistA').style.opacity = 0;
	document.getElementById('ventSistB').style.opacity = 0;
	document.getElementById('ventSistC').style.opacity = 0;
	document.getElementById('ventUPS').style.opacity = 0;
	document.getElementById('ventCAD').style.opacity = 0;
	document.getElementById('ventCE').style.opacity = 0;
	document.getElementById('ventCR').style.opacity = 0;
	};
	function mostrarDivSist6(){
	document.getElementById('inicioMain').style.opacity = 0;
	document.getElementById('ventSist17').style.opacity = 0;
	document.getElementById('ventSist16').style.opacity = 0;
	document.getElementById('ventSist15').style.opacity = 0;
	document.getElementById('ventSist14').style.opacity = 0;
	document.getElementById('ventSist13').style.opacity = 0;
	document.getElementById('ventSist12').style.opacity = 0;
	document.getElementById('ventSist11').style.opacity = 0;
	document.getElementById('ventSist10').style.opacity = 0;
	document.getElementById('ventSist9').style.opacity = 0;
	document.getElementById('ventSist8').style.opacity = 0;
	document.getElementById('ventSist7').style.opacity = 0;
	document.getElementById('ventSist6').style.opacity = 0.9;
	document.getElementById('ventSist5').style.opacity = 0;
	document.getElementById('ventSistA').style.opacity = 0;
	document.getElementById('ventSistB').style.opacity = 0;
	document.getElementById('ventSistC').style.opacity = 0;
	document.getElementById('ventUPS').style.opacity = 0;
	document.getElementById('ventCAD').style.opacity = 0;
	document.getElementById('ventCE').style.opacity = 0;
	document.getElementById('ventCR').style.opacity = 0;
	};


		function mostrarDivSist5(){
	document.getElementById('inicioMain').style.opacity = 0;
	document.getElementById('ventSist17').style.opacity = 0;
	document.getElementById('ventSist16').style.opacity = 0;
	document.getElementById('ventSist15').style.opacity = 0;
	document.getElementById('ventSist14').style.opacity = 0;
	document.getElementById('ventSist13').style.opacity = 0;
	document.getElementById('ventSist12').style.opacity = 0;
	document.getElementById('ventSist11').style.opacity = 0;
	document.getElementById('ventSist10').style.opacity = 0;
	document.getElementById('ventSist9').style.opacity = 0;
	document.getElementById('ventSist8').style.opacity = 0;
	document.getElementById('ventSist7').style.opacity = 0;
	document.getElementById('ventSist6').style.opacity = 0;
	document.getElementById('ventSist5').style.opacity = 0.9;
	document.getElementById('ventSistA').style.opacity = 0;
	document.getElementById('ventSistB').style.opacity = 0;
	document.getElementById('ventSistC').style.opacity = 0;
	document.getElementById('ventUPS').style.opacity = 0;
	document.getElementById('ventCAD').style.opacity = 0;
	document.getElementById('ventCE').style.opacity = 0;
	document.getElementById('ventCR').style.opacity = 0;
	};
	function mostrarDivSistA(){
	document.getElementById('inicioMain').style.opacity = 0;
	document.getElementById('ventSist17').style.opacity = 0;
	document.getElementById('ventSist16').style.opacity = 0;
	document.getElementById('ventSist15').style.opacity = 0;
	document.getElementById('ventSist14').style.opacity = 0;
	document.getElementById('ventSist13').style.opacity = 0;
	document.getElementById('ventSist12').style.opacity = 0;
	document.getElementById('ventSist11').style.opacity = 0;
	document.getElementById('ventSist10').style.opacity = 0;
	document.getElementById('ventSist9').style.opacity = 0;
	document.getElementById('ventSist8').style.opacity = 0;
	document.getElementById('ventSist7').style.opacity = 0;
	document.getElementById('ventSist6').style.opacity = 0;
	document.getElementById('ventSist5').style.opacity = 0;
	document.getElementById('ventSistA').style.opacity = 0.9;
	document.getElementById('ventSistB').style.opacity = 0;
	document.getElementById('ventSistC').style.opacity = 0;
	document.getElementById('ventUPS').style.opacity = 0;
	document.getElementById('ventCAD').style.opacity = 0;
	document.getElementById('ventCE').style.opacity = 0;
	document.getElementById('ventCR').style.opacity = 0;
	};
	function mostrarDivSistB(){
	document.getElementById('inicioMain').style.opacity = 0;
	document.getElementById('ventSist17').style.opacity = 0;
	document.getElementById('ventSist16').style.opacity = 0;
	document.getElementById('ventSist15').style.opacity = 0;
	document.getElementById('ventSist14').style.opacity = 0;
	document.getElementById('ventSist13').style.opacity = 0;
	document.getElementById('ventSist12').style.opacity = 0;
	document.getElementById('ventSist11').style.opacity = 0;
	document.getElementById('ventSist10').style.opacity = 0;
	document.getElementById('ventSist9').style.opacity = 0;
	document.getElementById('ventSist8').style.opacity = 0;
	document.getElementById('ventSist7').style.opacity = 0;
	document.getElementById('ventSist6').style.opacity = 0;
	document.getElementById('ventSist5').style.opacity = 0;
	document.getElementById('ventSistA').style.opacity = 0;
	document.getElementById('ventSistB').style.opacity = 0.9;
	document.getElementById('ventSistC').style.opacity = 0;
	document.getElementById('ventUPS').style.opacity = 0;
	document.getElementById('ventCAD').style.opacity = 0;
	document.getElementById('ventCE').style.opacity = 0;
	document.getElementById('ventCR').style.opacity = 0;
	};
	function mostrarDivSistC(){
	document.getElementById('inicioMain').style.opacity = 0;
	document.getElementById('ventSist17').style.opacity = 0;
	document.getElementById('ventSist16').style.opacity = 0;
	document.getElementById('ventSist15').style.opacity = 0;
	document.getElementById('ventSist14').style.opacity = 0;
	document.getElementById('ventSist13').style.opacity = 0;
	document.getElementById('ventSist12').style.opacity = 0;
	document.getElementById('ventSist11').style.opacity = 0;
	document.getElementById('ventSist10').style.opacity = 0;
	document.getElementById('ventSist9').style.opacity = 0;
	document.getElementById('ventSist8').style.opacity = 0;
	document.getElementById('ventSist7').style.opacity = 0;
	document.getElementById('ventSist6').style.opacity = 0;
	document.getElementById('ventSist5').style.opacity = 0;
	document.getElementById('ventSistA').style.opacity = 0;
	document.getElementById('ventSistB').style.opacity = 0;
	document.getElementById('ventSistC').style.opacity = 0.9;
	document.getElementById('ventUPS').style.opacity = 0;
	document.getElementById('ventCAD').style.opacity = 0;
	document.getElementById('ventCE').style.opacity = 0;
	document.getElementById('ventCR').style.opacity = 0;
	};
	function mostrarUPS(){
	document.getElementById('inicioMain').style.opacity = 0;
	document.getElementById('ventSist17').style.opacity = 0;
	document.getElementById('ventSist16').style.opacity = 0;
	document.getElementById('ventSist15').style.opacity = 0;
	document.getElementById('ventSist14').style.opacity = 0;
	document.getElementById('ventSist13').style.opacity = 0;
	document.getElementById('ventSist12').style.opacity = 0;
	document.getElementById('ventSist11').style.opacity = 0;
	document.getElementById('ventSist10').style.opacity = 0;
	document.getElementById('ventSist9').style.opacity = 0;
	document.getElementById('ventSist8').style.opacity = 0;
	document.getElementById('ventSist7').style.opacity = 0;
	document.getElementById('ventSist6').style.opacity = 0;
	document.getElementById('ventSist5').style.opacity = 0;
	document.getElementById('ventSistA').style.opacity = 0;
	document.getElementById('ventSistB').style.opacity = 0;
	document.getElementById('ventSistC').style.opacity = 0;
	document.getElementById('ventUPS').style.opacity = 0.9;
	document.getElementById('ventCAD').style.opacity = 0;
	document.getElementById('ventCE').style.opacity = 0;
	document.getElementById('ventCR').style.opacity = 0;
	};
	
	function mostrarCAD(){
	document.getElementById('inicioMain').style.opacity = 0;
	document.getElementById('ventSist17').style.opacity = 0;
	document.getElementById('ventSist16').style.opacity = 0;
	document.getElementById('ventSist15').style.opacity = 0;
	document.getElementById('ventSist14').style.opacity = 0;
	document.getElementById('ventSist13').style.opacity = 0;
	document.getElementById('ventSist12').style.opacity = 0;
	document.getElementById('ventSist11').style.opacity = 0;
	document.getElementById('ventSist10').style.opacity = 0;
	document.getElementById('ventSist9').style.opacity = 0;
	document.getElementById('ventSist8').style.opacity = 0;
	document.getElementById('ventSist7').style.opacity = 0;
	document.getElementById('ventSist6').style.opacity = 0;
	document.getElementById('ventSist5').style.opacity = 0;
	document.getElementById('ventSistA').style.opacity = 0;
	document.getElementById('ventSistB').style.opacity = 0;
	document.getElementById('ventSistC').style.opacity = 0;
	document.getElementById('ventUPS').style.opacity = 0;
	document.getElementById('ventCAD').style.opacity = 0.9;
	document.getElementById('ventCE').style.opacity = 0;
	document.getElementById('ventCR').style.opacity = 0;
	};
	function mostrarCE(){
	document.getElementById('inicioMain').style.opacity = 0;
	document.getElementById('ventSist17').style.opacity = 0;
	document.getElementById('ventSist16').style.opacity = 0;
	document.getElementById('ventSist15').style.opacity = 0;
	document.getElementById('ventSist14').style.opacity = 0;
	document.getElementById('ventSist13').style.opacity = 0;
	document.getElementById('ventSist12').style.opacity = 0;
	document.getElementById('ventSist11').style.opacity = 0;
	document.getElementById('ventSist10').style.opacity = 0;
	document.getElementById('ventSist9').style.opacity = 0;
	document.getElementById('ventSist8').style.opacity = 0;
	document.getElementById('ventSist7').style.opacity = 0;
	document.getElementById('ventSist6').style.opacity = 0;
	document.getElementById('ventSist5').style.opacity = 0;
	document.getElementById('ventSistA').style.opacity = 0;
	document.getElementById('ventSistB').style.opacity = 0;
	document.getElementById('ventSistC').style.opacity = 0;
	document.getElementById('ventUPS').style.opacity = 0;
	document.getElementById('ventCAD').style.opacity = 0;
	document.getElementById('ventCE').style.opacity = 0.9;
	document.getElementById('ventCR').style.opacity = 0;
	};
	function mostrarCR(){
	document.getElementById('inicioMain').style.opacity = 0;
	document.getElementById('ventSist17').style.opacity = 0;
	document.getElementById('ventSist16').style.opacity = 0;
	document.getElementById('ventSist15').style.opacity = 0;
	document.getElementById('ventSist14').style.opacity = 0;
	document.getElementById('ventSist13').style.opacity = 0;
	document.getElementById('ventSist12').style.opacity = 0;
	document.getElementById('ventSist11').style.opacity = 0;
	document.getElementById('ventSist10').style.opacity = 0;
	document.getElementById('ventSist9').style.opacity = 0;
	document.getElementById('ventSist8').style.opacity = 0;
	document.getElementById('ventSist7').style.opacity = 0;
	document.getElementById('ventSist6').style.opacity = 0;
	document.getElementById('ventSist5').style.opacity = 0;
	document.getElementById('ventSistA').style.opacity = 0;
	document.getElementById('ventSistB').style.opacity = 0;
	document.getElementById('ventSistC').style.opacity = 0;
	document.getElementById('ventUPS').style.opacity = 0;
	document.getElementById('ventCAD').style.opacity = 0;
	document.getElementById('ventCE').style.opacity = 0;
	document.getElementById('ventCR').style.opacity = 0.9;
	};







/* PATRIMONIOS AUTÓNOMOS*/















	function mostrarDivTorre1(){
	document.getElementById('divTorre1').style.opacity = 0.9;
	document.getElementById('divTorre2').style.opacity = 0;
	document.getElementById('divBAC1').style.opacity = 0;
	document.getElementById('divBAC2').style.opacity = 0;
	document.getElementById('divBAF1').style.opacity = 0;
	document.getElementById('divBAF2').style.opacity = 0;
	document.getElementById('divBAF3').style.opacity = 0;
	document.getElementById('divBAF4').style.opacity = 0;
	document.getElementById('divLobby').style.opacity = 0;
	document.getElementById('divOfAdmon').style.opacity = 0;
	document.getElementById('divOfMonitoreo').style.opacity = 0;
	document.getElementById('divECOP').style.opacity = 0;
	};
	function mostrarDivTorre2(){
	document.getElementById('divTorre1').style.opacity = 0;
	document.getElementById('divTorre2').style.opacity = 0.9;
	document.getElementById('divBAC1').style.opacity = 0;
	document.getElementById('divBAC2').style.opacity = 0;
	document.getElementById('divBAF1').style.opacity = 0;
	document.getElementById('divBAF2').style.opacity = 0;
	document.getElementById('divBAF3').style.opacity = 0;
	document.getElementById('divBAF4').style.opacity = 0;
	document.getElementById('divLobby').style.opacity = 0;
	document.getElementById('divOfAdmon').style.opacity = 0;
	document.getElementById('divOfMonitoreo').style.opacity = 0;
	document.getElementById('divECOP').style.opacity = 0;
	};
	function mostrarDivBAC1(){
	document.getElementById('divTorre1').style.opacity = 0;
	document.getElementById('divTorre2').style.opacity = 0;
	document.getElementById('divBAC1').style.opacity = 0.9;
	document.getElementById('divBAC2').style.opacity = 0;
	document.getElementById('divBAF1').style.opacity = 0;
	document.getElementById('divBAF2').style.opacity = 0;
	document.getElementById('divBAF3').style.opacity = 0;
	document.getElementById('divBAF4').style.opacity = 0;
	document.getElementById('divLobby').style.opacity = 0;
	document.getElementById('divOfAdmon').style.opacity = 0;
	document.getElementById('divOfMonitoreo').style.opacity = 0;	
	document.getElementById('divECOP').style.opacity = 0;
	};
	function mostrarDivBAC2(){
	document.getElementById('divTorre1').style.opacity = 0;
	document.getElementById('divTorre2').style.opacity = 0;
	document.getElementById('divBAC1').style.opacity = 0;
	document.getElementById('divBAC2').style.opacity = 0.9;
	document.getElementById('divBAF1').style.opacity = 0;
	document.getElementById('divBAF2').style.opacity = 0;
	document.getElementById('divBAF3').style.opacity = 0;
	document.getElementById('divBAF4').style.opacity = 0;
	document.getElementById('divLobby').style.opacity = 0;
	document.getElementById('divOfAdmon').style.opacity = 0;
	document.getElementById('divOfMonitoreo').style.opacity = 0;	
	document.getElementById('divECOP').style.opacity = 0;
	};
	function mostrarDivBAF1(){
	document.getElementById('divTorre1').style.opacity = 0;
	document.getElementById('divTorre2').style.opacity = 0;
	document.getElementById('divBAC1').style.opacity = 0;
	document.getElementById('divBAC2').style.opacity = 0;
	document.getElementById('divBAF1').style.opacity = 0.9;
	document.getElementById('divBAF2').style.opacity = 0;
	document.getElementById('divBAF3').style.opacity = 0;
	document.getElementById('divBAF4').style.opacity = 0;
	document.getElementById('divLobby').style.opacity = 0;
	document.getElementById('divOfAdmon').style.opacity = 0;
	document.getElementById('divOfMonitoreo').style.opacity = 0;	
	document.getElementById('divECOP').style.opacity = 0;
	};
	function mostrarDivBAF2(){
	document.getElementById('divTorre1').style.opacity = 0;
	document.getElementById('divTorre2').style.opacity = 0;
	document.getElementById('divBAC1').style.opacity = 0;
	document.getElementById('divBAC2').style.opacity = 0;
	document.getElementById('divBAF1').style.opacity = 0;
	document.getElementById('divBAF2').style.opacity = 0.9;
	document.getElementById('divBAF3').style.opacity = 0;
	document.getElementById('divBAF4').style.opacity = 0;
	document.getElementById('divLobby').style.opacity = 0;
	document.getElementById('divOfAdmon').style.opacity = 0;
	document.getElementById('divOfMonitoreo').style.opacity = 0;	
	document.getElementById('divECOP').style.opacity = 0;
	};
	function mostrarDivBAF3(){
	document.getElementById('divTorre1').style.opacity = 0;
	document.getElementById('divTorre2').style.opacity = 0;
	document.getElementById('divBAC1').style.opacity = 0;
	document.getElementById('divBAC2').style.opacity = 0;
	document.getElementById('divBAF1').style.opacity = 0;
	document.getElementById('divBAF2').style.opacity = 0;
	document.getElementById('divBAF3').style.opacity = 0.9;
	document.getElementById('divBAF4').style.opacity = 0;
	document.getElementById('divLobby').style.opacity = 0;
	document.getElementById('divOfAdmon').style.opacity = 0;
	document.getElementById('divOfMonitoreo').style.opacity = 0;	
	document.getElementById('divECOP').style.opacity = 0;
	};
	function mostrarDivBAF4(){
	document.getElementById('divTorre1').style.opacity = 0;
	document.getElementById('divTorre2').style.opacity = 0;
	document.getElementById('divBAC1').style.opacity = 0;
	document.getElementById('divBAC2').style.opacity = 0;
	document.getElementById('divBAF1').style.opacity = 0;
	document.getElementById('divBAF2').style.opacity = 0;
	document.getElementById('divBAF3').style.opacity = 0;
	document.getElementById('divBAF4').style.opacity = 0.9;
	document.getElementById('divLobby').style.opacity = 0;
	document.getElementById('divOfAdmon').style.opacity = 0;
	document.getElementById('divOfMonitoreo').style.opacity = 0;	
	document.getElementById('divECOP').style.opacity = 0;
	};
	function mostrarDivLobby(){
	document.getElementById('divTorre1').style.opacity = 0;
	document.getElementById('divTorre2').style.opacity = 0;
	document.getElementById('divBAC1').style.opacity = 0;
	document.getElementById('divBAC2').style.opacity = 0;
	document.getElementById('divBAF1').style.opacity = 0;
	document.getElementById('divBAF2').style.opacity = 0;
	document.getElementById('divBAF3').style.opacity = 0;
	document.getElementById('divBAF4').style.opacity = 0;
	document.getElementById('divLobby').style.opacity = 0.9;
	document.getElementById('divOfAdmon').style.opacity = 0;
	document.getElementById('divOfMonitoreo').style.opacity = 0;
	document.getElementById('divECOP').style.opacity = 0;
	};
	function mostrarDivOfAdmon(){
	document.getElementById('divTorre1').style.opacity = 0;
	document.getElementById('divTorre2').style.opacity = 0;
	document.getElementById('divBAC1').style.opacity = 0;
	document.getElementById('divBAC2').style.opacity = 0;
	document.getElementById('divBAF1').style.opacity = 0;
	document.getElementById('divBAF2').style.opacity = 0;
	document.getElementById('divBAF3').style.opacity = 0;
	document.getElementById('divBAF4').style.opacity = 0;
	document.getElementById('divLobby').style.opacity = 0;
	document.getElementById('divOfAdmon').style.opacity = 0.9;
	document.getElementById('divOfMonitoreo').style.opacity = 0;
	document.getElementById('divECOP').style.opacity = 0;
	};

	function mostrarDivOfMonitoreo(){
	document.getElementById('divTorre1').style.opacity = 0;
	document.getElementById('divTorre2').style.opacity = 0;
	document.getElementById('divBAC1').style.opacity = 0;
	document.getElementById('divBAC2').style.opacity = 0;
	document.getElementById('divBAF1').style.opacity = 0;
	document.getElementById('divBAF2').style.opacity = 0;
	document.getElementById('divBAF3').style.opacity = 0;
	document.getElementById('divBAF4').style.opacity = 0;
	document.getElementById('divLobby').style.opacity = 0;
	document.getElementById('divOfAdmon').style.opacity = 0;
	document.getElementById('divOfMonitoreo').style.opacity = 0.9;	
	document.getElementById('divECOP').style.opacity = 0;
	};
	function mostrarDivECOPlanta(){
	document.getElementById('divTorre1').style.opacity = 0;
	document.getElementById('divTorre2').style.opacity = 0;
	document.getElementById('divBAC1').style.opacity = 0;
	document.getElementById('divBAC2').style.opacity = 0;
	document.getElementById('divBAF1').style.opacity = 0;
	document.getElementById('divBAF2').style.opacity = 0;
	document.getElementById('divBAF3').style.opacity = 0;
	document.getElementById('divBAF4').style.opacity = 0;
	document.getElementById('divLobby').style.opacity = 0;
	document.getElementById('divOfAdmon').style.opacity = 0;
	document.getElementById('divOfMonitoreo').style.opacity = 0;	
	document.getElementById('divECOP').style.opacity = 0.9;
	};